### ISSUE TITLE
can't work with React.memo

### ISSUE THREAD

**Issue by GFwer** [welldone-software/why-did-you-render#10]
I've created a memo Component, but it's no output in my console.

when I remove memo function in my component, it works.

Is it because the why-did-you-render does not support React.memo?

**Comment by vzaidman** [comment]
fixed in version 2.6.0

**Comment by Hypnosphi** [comment]
Still doesn't work if `React.memo` is applied to a class component. Of course, it's more natural to use `PureComponent` for classes, but in my case it's some third party component
