### ISSUE TITLE
False positive with nested children props changes

### ISSUE THREAD

**Issue by Hypnosphi** [welldone-software/why-did-you-render#117]
https://codesandbox.io/s/why-did-you-render-sandbox-vorhj?file=/src/index.js

Here, in
```js
<BigListPureComponent style={bigListStyle}>
  <Child count={count} />
</BigListPureComponent>
```

`props.children.props.count` changes, so the elements are not deep equal. But WDYR still complains:
> Object {BigListPureComponent: function BigListPureComponent()}
BigListPureComponent: function BigListPureComponent() {}
"Re-rendered because of props changes:" 
props.children
different React elements (remember that the <jsx/> syntax always produces a *NEW* immutable React element so a component that receives <jsx/> as props always re-renders.). (more info at http://bit.ly/wdyr02) 

This is introduced in 4.2.0

**Comment by vzaidman** [comment]
fixed in v4.2.1

**Comment by Hypnosphi** [comment]
It still reproduces with multiple children: https://codesandbox.io/s/why-did-you-render-sandbox-tbhxj?file=/src/index.js

```
<BigListPureComponent style={bigListStyle}>
  <Child count={count} />
  <div />
</BigListPureComponent>
```

**Comment by vzaidman** [comment]
fixed in v4.2.2!
sorry for the delay
