### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by hrazmsft** [welldone-software/why-did-you-render#196]
I tried to add this lib to my Typescript project (with new the JSX transformation), but I get an error in all of my React code:
> Could not find a declaration file for module '@welldone-software/why-did-you-render/jsx-runtime'

This is my `wdyr.ts` file:
```
/// <reference types="@welldone-software/why-did-you-render" />

import React from 'react';

if (process.env.NODE_ENV === 'development') {
    const whyDidYouRender = require('@welldone-software/why-did-you-render');
    whyDidYouRender(React, {
        trackAllPureComponents: true,
    });
}
```

What is the correct way to add the types?

**Comment by vzaidman** [comment]
seems like there are no types for the transformation indeed. I'll try adding them asap.

**Comment by hrazmsft** [comment]
If you already know what should be changed in the `d.ts` file, please let me know so I integrate WDYR into my project ASAP.

**Comment by vzaidman** [comment]
hey @hrazmsft !
using
```
    // tsconfig.js
    "jsx": "react-jsx",
    "jsxImportSource": "@welldone-software/why-did-you-render",
```
I don't see any problem.

How do I reproduce this issue?

**Comment by hrazmsft** [comment]
Exactly like that! This is how I have configured my project. Then all the jsx code marked with the error above.

I will try to create a repo that will repro this issue and post it here.

**Comment by hrazmsft** [comment]
Hi @vzaidman ,

It is easy to reproduce:
1. Create an empty React app with a TypeScript template.
2. Add the package `@welldone-software/why-did-you-render` via yarn or npm
3. Add `"jsxImportSource": "@welldone-software/why-did-you-render"` to the tsconfig.json file
4. An error will show up

Here is an example repo with the error: https://github.com/hrazmsft/wdyr-repro

Screenshots:

![image](https://user-images.githubusercontent.com/66222191/118955632-8a6b7400-b967-11eb-8742-2bfc2e94066c.png)


![image](https://user-images.githubusercontent.com/66222191/118955820-ba1a7c00-b967-11eb-87c1-b20157b9d52c.png)

**Comment by vzaidman** [comment]
fixed in [v6.1.4](https://github.com/welldone-software/why-did-you-render/releases/tag/v6.1.4)

**Comment by jafin** [comment]
@vzaidman ,  I am still seeing a similar error to the OP (v6.2.0).   The jsx-runtime.d.ts does appear in the distribution.

Do the additional ts files need to be referenced in the package.json ? ie.?

```package.json
"files": [
...
"jsx-dev-runtime.d.ts"
"jsx-runtime.d.ts"
```

**Comment by vzaidman** [comment]
> @vzaidman , I am still seeing a similar error to the OP (v6.2.0). The jsx-runtime.d.ts does appear in the distribution.
> 
> Do the additional ts files need to be referenced in the package.json ? ie.
> 
> ```json
> "files": [
> ...
> "jsx-dev-runtime.d.ts"
> "jsx-runtime.d.ts"
> ```

You are totally right.

I've just pushed [version 6.2.1](https://github.com/welldone-software/why-did-you-render/releases/tag/v6.2.1) with the types added in "files".

Thank you!
