### ISSUE TITLE
Doesn't work with dom components wrapped in React.memo

### ISSUE THREAD

**Issue by Hypnosphi** [welldone-software/why-did-you-render#66]
```
const Svg = React.memo('svg');

ReactDom.render(<Svg />, element);
```

Throws
> TypeError: e.apply is not a function

**Comment by vzaidman** [comment]
fixing

**Comment by vzaidman** [comment]
fixed in 3.3.8:
https://codesandbox.io/s/welldone-softwarewhy-did-you-render-memo-a-text-example-pzn3b

**Comment by JackHowa** [comment]
I'm still seeing this using a custom memo check 

```
import React, { memo } from 'react';
import PropTypes from 'prop-types';
import { StyledContainer } from './styles';
import deepCompareUpdate from '~/utils/deepCompareUpdate';

function Item({ things, title, latitude, longitude }) {
  return (
    <StyledContainer>
      <div>
        <h5>{title}</h5>
        {things.map(thing => (
          <p key={thing}>{thing}</p>
        ))}
      </div>
    </StyledContainer>
  );
}

Item.propTypes = {
  title: PropTypes.string,
  things: PropTypes.array,
};

Item.defaultProps = {
  title: '',
  things: [],
};

export default memo(Item, deepCompareUpdate);


// deepCompareUpdate
import isEqual from 'react-fast-compare';
// fast compare is like lodash's isEqual but suited for react
// note: neither solve for checking children components
// https://formidable.com/blog/2018/introducing-react-fast-compare/

const deepCompareUpdate = (props, nextProps) =>
  Object.keys(props).some(k => !isEqual(props[k], nextProps[k]));

export default deepCompareUpdate;

```

![Screen Shot 2019-12-19 at 11 10 25 AM](https://user-images.githubusercontent.com/5950956/71193698-29121380-2250-11ea-9a68-9531f6c9bfbd.png)

**Comment by vzaidman** [comment]
@JackHowa where's the problem?
